apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: gcr.io/kube-project-385314/flaskapp:1.0.1
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
